<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PROJET THE LEAGUE</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Ubuntu:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/projet-the-league/assets/style/style.css">
</head>

<body>
    <header class="site-header">
        <span class="site-header__logo">The League</span>
        <nav class="site-header__nav">
            <ul>
                <li><a href="index.php">Les Teams</a></li>
                <li><a href="index.php?route=player">Les Players</a></li>
                <li><a href="index.php?route=matchs">Les Matchs</a></li>
            </ul>
        </nav>
    </header>
    <?php
    require "templates/$template.phtml";
    ?>
</body>

</html>